CREATE TABLE IF NOT EXISTS users (
   id VARCHAR(40) PRIMARY KEY,
   first_name VARCHAR(50) NOT NULL,
   last_name VARCHAR(50) NOT NULL,
   email VARCHAR(150) NOT NULL,
   password VARCHAR(250) NOT NULL,
   salt bytea NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS todos (
   id VARCHAR(40) PRIMARY KEY,
   title VARCHAR(50) NOT NULL,
   description VARCHAR(255),
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);